---
apiVersion: v1
kind: Namespace
metadata:
  name: push-to-k8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: push-to-k8s
  namespace: push-to-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: push-to-k8s
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: push-to-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: push-to-k8s
subjects:
- kind: ServiceAccount
  name: push-to-k8s
  namespace: push-to-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-to-k8s
  namespace: push-to-k8s
  labels:
    app: push-to-k8s
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: push-to-k8s
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
      labels:
        app: push-to-k8s
    spec:
      serviceAccountName: push-to-k8s
      containers:
        - name: push-to-k8s
          image: cube8021/push-to-k8s:test
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
            - name: DEBUG
              value: "true"  # Enable debug for testing
            - name: METRICS_PORT
              value: "9090"
            - name: EXCLUDE_NAMESPACE_LABEL
              value: ""
            - name: SYNC_INTERVAL
              value: "5"  # 5 minutes for faster testing
            - name: NAMESPACE
              value: "push-to-k8s"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
