---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: push-to-k8s
  namespace: push-to-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: push-to-k8s
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: push-to-k8s
  namespace: push-to-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: push-to-k8s
  name: push-to-k8s
  namespace: push-to-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: push-to-k8s
  template:
    metadata:
      labels:
        app: push-to-k8s
    spec:
      serviceAccount: push-to-k8s
      serviceAccountName: push-to-k8s
      containers:
      - args:
        - /root/bin/main.sh
        env:
        - name: SLEEP
          value: "60"
        - name: SYNCNAMESPACE
          value: "push-to-k8s"
        - name: LABELSELECTOR
          value: "exclude"
        image: supporttools/kube-builder
        imagePullPolicy: IfNotPresent
        name: push-to-k8s
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - mountPath: /root/bin/
          name: push-to-k8s
      volumes:
      - configMap:
          defaultMode: 493
          items:
          - key: main.sh
            mode: 0755
            path: main.sh
          name: push-to-k8s
          optional: false
        name: push-to-k8s