apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: push-to-k8s
  labels:
    app: push-to-k8s
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - list
      - get
      - watch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - list
      - get
      - watch
      - create
      - update
