apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "push-to-k8s.fullname" . }}
  labels:
    {{- include "push-to-k8s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "push-to-k8s.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "push-to-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}