apiVersion: v1
kind: Service
metadata:
  name: "push-to-k8s"
  labels:
    app: "push-to-k8s"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app: "push-to-k8s"
