apiVersion: v1
kind: Service
metadata:
  name: {{ include "push-to-k8s.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "push-to-k8s.labels" . | nindent 4 }}
  {{- if .Values.settings.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.settings.metrics.port }}"
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "push-to-k8s.selectorLabels" . | nindent 4 }}
